# Esto es lo que ya tenías para la configuración del logger
[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

# --- AÑADE ESTE NUEVO BLOQUE DEBAJO ---
[theme]
# Color de fondo principal (un gris oscuro)
backgroundColor="#212121"

# Color de fondo secundario (para elementos como la sidebar, si se muestra)
secondaryBackgroundColor="#2E2E2E"

# Color del texto principal
textColor="#FFFFFF"

# Fuente principal
font="sans serif"
